### ISSUE TITLE
managerserver fails to start if the cluster name is not in lowercase

### ISSUE THREAD

**Issue by jazzl0ver** [cloudstax/firecamp#5]
```
I1124 15:39:09.383539       1 route53.go:133] zone is not for domain FireCamp-UAT-firecamp.com zone {
  CallerReference: "FireCamp-Route53H-1TC3D958X5KBG",
  Config: {
    PrivateZone: true
  },
  Id: "/hostedzone/ABCD",
  Name: "firecamp-uat-firecamp.com.",
  ResourceRecordSetCount: 2
} requuid
E1124 15:39:09.383573       1 route53.go:52] CreateHostedZone error DomainNotFound domain FireCamp-UAT-firecamp.com vpc vpc-0000000 us-east-1 requuid
E1124 15:39:09.383587       1 server_start.go:49] GetOrCreateHostedZoneIDByName error DomainNotFound domain FireCamp-UAT-firecamp.com vpcID vpc-000000
F1124 15:39:09.383596       1 main.go:171] StartServer error DomainNotFound
```

**Comment by JuniusLuo** [comment]
@jazzl0ver thanks for reporting the issue! 
yes, it is a bug. route53 uses lowercase. will add a fix.

**Comment by JuniusLuo** [comment]
This issue is a more general issue. The dns service such as AWS Route53 does not distinguish the upper case and lower case. For example, MyService1.FireCamp-UAT-firecamp.com is the same with myservice1.firecamp-uat-firecamp.com. 

If the names of 2 clusters have the same letters (one is lower case, the other is upper case), the services of these 2 clusters will share the same domain. If both clusters happen to have the service with the same name, they will share the same AWS Route53 records. This will mess up the services.

Or the names of 2 services in one cluster have the same letters, this will happen as well. AWS ECS treats them as 2 different services, Docker Swarm rejects the second service creation.

Usually no one will create the cluster or service with the same name (lower/upper letters). But to prevent the corner case from happening, we will limit the cluster name to use the lower case letters only in AWS CloudFormation template, and convert the service name to lower case as well.

**Comment by cloudstax** [comment]
The fix is committed to master. The 0.9.1 release will include it. Please let us know if you hit any issue. Thanks!
